### ISSUE TITLE
Discussion: Config vs Option

### ISSUE THREAD

**Issue by pk-work** [SAP/neonbee#44]
We should clarify what's the defference between option and config. Why is the server port an option, but timezone a config?

**Comment by kristian** [comment]
A config is for me something persistent you want to likely store and deploy in a file, while an option is something volatile that you want to specify when starting.

E.g. the server port: is an option and a config. You might want to specify the port in a config file, however having an option to overrule the config is a thing you likely want to have.

The timezone is IMHO nothing you'd like to specify as a command line option, because you just "pick it once" and set it in a config.

Current working directory: obvious example of a paeamter you never want to set as a config but always as an option.

**Comment by pk-work** [comment]
Okay, I agree to this.
